spring.application.name=guardrailengine

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/virality_db
spring.datasource.username=virality_user
spring.datasource.password=virality_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Server
server.port=8080